version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shop_platform
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://shop_user:shop_password@db:5432/shop_platform
      - DEBUG=True

volumes:
  postgres_data:
  media_volume:
