# Generated by Django 4.1.13 on 2025-07-24 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_chatmessage_deliverymethod_productreview_shipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('closed', 'بسته شده'), ('waiting', 'در انتظار'), ('archived', 'بایگانی شده')], default='waiting', max_length=20)),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0, help_text='Average response time in seconds')),
                ('customer_satisfaction', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_chats', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='shop.store')),
            ],
            options={
                'verbose_name': 'اتاق گفتگو',
                'verbose_name_plural': 'اتاق\u200cهای گفتگو',
                'db_table': 'realtime_chat_room',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shop.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسه گفتگوی لحظه\u200cای',
                'verbose_name_plural': 'جلسات گفتگوی لحظه\u200cای',
                'db_table': 'realtime_chat_session',
            },
        ),
        migrations.CreateModel(
            name='RealtimeChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'پیام جدید'), ('agent_assigned', 'اختصاص مشاور'), ('chat_closed', 'بستن گفتگو'), ('customer_waiting', 'انتظار مشتری')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_chat_notifications', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_notifications', to='shop.chatroom')),
            ],
            options={
                'verbose_name': 'اعلان گفتگوی لحظه\u200cای',
                'verbose_name_plural': 'اعلانات گفتگوی لحظه\u200cای',
                'db_table': 'realtime_chat_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('file', 'فایل'), ('system', 'سیستم'), ('product', 'محصول')], default='text', max_length=20)),
                ('content', models.TextField(verbose_name='محتوا')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام گفتگوی لحظه\u200cای',
                'verbose_name_plural': 'پیام\u200cهای گفتگوی لحظه\u200cای',
                'db_table': 'realtime_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان قالب')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('category', models.CharField(max_length=50, verbose_name='دسته\u200cبندی')),
                ('shortcut', models.CharField(blank=True, max_length=20, verbose_name='میانبر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_templates', to='shop.store')),
            ],
            options={
                'verbose_name': 'قالب پاسخ سریع',
                'verbose_name_plural': 'قالب\u200cهای پاسخ سریع',
                'db_table': 'chat_template',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='18:00')),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday)')),
                ('welcome_message', models.TextField(default='سلام! چطور می\u200cتونم کمکتون کنم؟')),
                ('offline_message', models.TextField(default='متاسفانه در حال حاضر آنلاین نیستیم. لطفا پیام بذارید.')),
                ('auto_assign_agent', models.BooleanField(default=True)),
                ('require_email', models.BooleanField(default=False)),
                ('allow_file_upload', models.BooleanField(default=True)),
                ('max_file_size', models.IntegerField(default=5, help_text='Max file size in MB')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='shop.store')),
            ],
            options={
                'verbose_name': 'تنظیمات گفتگو',
                'verbose_name_plural': 'تنظیمات گفتگو',
                'db_table': 'chat_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('max_concurrent_chats', models.IntegerField(default=5)),
                ('current_chat_count', models.IntegerField(default=0)),
                ('departments', models.JSONField(default=list, help_text='Departments this agent handles')),
                ('languages', models.JSONField(default=list, help_text='Languages agent speaks')),
                ('total_chats', models.IntegerField(default=0)),
                ('avg_response_time', models.IntegerField(default=0)),
                ('customer_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_agents', to='shop.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشاور گفتگو',
                'verbose_name_plural': 'مشاوران گفتگو',
                'db_table': 'realtime_chat_agent',
            },
        ),
    ]
